name: firebase_purchase
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  firebase_auth: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/cart.png


